"""
LLM Patch Measurement Engine for Green Code Refactoring.

Measures energy consumption of LLM-generated patches using the same
infrastructure as measure_instance.py (which works correctly).

NEW: Includes automatic syntax fixing for common LLM errors (indentation, etc.)

Supports all prompt types:
- zero_shot: Zero-Shot prompting
- cot: Chain-of-Thought prompting
- self_collab: Self-Collaboration (multi-turn)
- ldb: LDB iterative refinement

MULTI-MODEL SUPPORT:
Results directory and model name can be specified via arguments.

Output format:
    data/processed/green/[MODEL]_[PROMPT_TYPE]_[STRATEGY]_k[REPS].json

Usage:
    python measure_llm_patches.py --strategy oracle --prompt-type cot --repetitions 5
    python measure_llm_patches.py --strategy oracle --prompt-type self_collab -k 3
    python measure_llm_patches.py --dataset data/processed/swe_perf_reduced.json -k 3
    
    # Multi-model support
    python measure_llm_patches.py --strategy oracle --prompt-type zero_shot -k 3 \
        --results-dir results/DeepSeek-Coder-V2/zs_oracle --model-name DeepSeek-Coder-V2
"""
import sys
import os
import json
import logging
import argparse
import tempfile
import shutil
import time
import re
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Any, Tuple

# --- PATH SETUP ---
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# --- IMPORTS ---
from scripts.measure_instance import SWEPerfMeasurer
from src.measurement.collector import MetricsCollector
from src.patch_engine import PatchEngine

# --- LOGGING ---
(PROJECT_ROOT / "logs").mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)-8s | %(message)s',
    handlers=[
        logging.FileHandler(PROJECT_ROOT / "logs" / "measure_llm_patches.log", mode='a'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger("MeasureLLMPatches")

# --- CONSTANTS ---
DEFAULT_DATASET = PROJECT_ROOT / "data" / "processed" / "swe_perf_reduced.json"
ORIGINAL_DATASET = PROJECT_ROOT / "data" / "original" / "swe_perf_original_20251124.json"
GREEN_OUTPUT_DIR = PROJECT_ROOT / "data" / "processed" / "green"
BASE_RESULTS_DIR = PROJECT_ROOT / "results"

# Default model name
DEFAULT_MODEL_NAME = "Qwen2.5-Coder-7B"

# Prompt type mappings
PROMPT_TYPE_TO_DIR_PREFIX = {
    "zero_shot": "zs",
    "cot": "cot",
    "self_collab": "sc",
    "ldb": "ldb"
}

PROMPT_TYPE_TO_CLEAN_NAME = {
    "zero_shot": "ZeroShot",
    "cot": "CoT",
    "self_collab": "SelfCollab",
    "ldb": "LDB"
}

# Metrics
GREEN_METRICS = [
    'cpu_energy_joules', 'gpu_energy_joules', 'total_energy_joules',
    'power_watts', 'carbon_grams', 'energy_efficiency'
]
EFFICIENCY_METRICS = [
    'duration_seconds', 'cpu_usage_mean_percent', 'cpu_usage_peak_percent',
    'ram_usage_mean_mb', 'ram_usage_peak_mb',
    'gpu_temperature_mean_celsius', 'gpu_temperature_peak_celsius'
]
ALL_METRICS = GREEN_METRICS + EFFICIENCY_METRICS
AGGREGATIONS = ['mean', 'std', 'min', 'max']


# =============================================================================
# SYNTAX FIXER - Auto-fixes common LLM syntax errors
# =============================================================================

class SyntaxFixer:
    """Auto-fixes common syntax errors in Python files generated by LLMs."""
    
    def __init__(self):
        self.fixes_applied = []
    
    def check_syntax(self, file_path: Path) -> Tuple[bool, str]:
        """Check if a Python file has valid syntax."""
        result = subprocess.run(
            ['python', '-m', 'py_compile', str(file_path)],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            return True, ""
        
        error_msg = result.stderr or result.stdout
        return False, error_msg
    
    def fix_file(self, file_path: Path) -> bool:
        """Attempt to fix syntax errors in a Python file."""
        file_path = Path(file_path)
        
        if not file_path.exists():
            return False
        
        # Step 1: Check if already valid
        is_valid, error_msg = self.check_syntax(file_path)
        if is_valid:
            return True
        
        logger.debug(f"    🔧 Fixing syntax in {file_path.name}: {error_msg[:100]}")
        
        # Step 2: Try autopep8 (aggressive mode)
        if self._try_autopep8(file_path):
            is_valid, _ = self.check_syntax(file_path)
            if is_valid:
                logger.info(f"    ✅ Fixed syntax with autopep8")
                return True
        
        # Step 3: Try manual fixes
        if self._try_manual_fixes(file_path, error_msg):
            is_valid, _ = self.check_syntax(file_path)
            if is_valid:
                logger.info(f"    ✅ Fixed syntax with manual fixes")
                return True
        
        # Step 4: Try autopep8 again after manual fixes
        if self._try_autopep8(file_path):
            is_valid, _ = self.check_syntax(file_path)
            if is_valid:
                logger.info(f"    ✅ Fixed syntax with autopep8 + manual")
                return True
        
        return False
    
    def _try_autopep8(self, file_path: Path) -> bool:
        """Try to fix with autopep8."""
        try:
            result = subprocess.run(
                ['autopep8', '--in-place', '--aggressive', '--aggressive', 
                 '--max-line-length', '150', str(file_path)],
                capture_output=True,
                text=True,
                timeout=30
            )
            return result.returncode == 0
        except FileNotFoundError:
            # autopep8 not installed, try without it
            return False
        except subprocess.TimeoutExpired:
            return False
        except Exception:
            return False
    
    def _try_manual_fixes(self, file_path: Path, error_msg: str) -> bool:
        """Try to manually fix common syntax errors."""
        try:
            with open(file_path, 'r') as f:
                lines = f.readlines()
            
            original_lines = lines.copy()
            
            # Fix 1: Normalize indentation (tabs to spaces)
            lines = [line.replace('\t', '    ') for line in lines]
            
            # Fix 2: Add 'pass' to empty blocks
            lines = self._fix_empty_blocks(lines)
            
            # Fix 3: Fix indentation after block statements
            lines = self._fix_block_indentation(lines, error_msg)
            
            # Fix 4: Remove trailing whitespace
            lines = [line.rstrip() + '\n' if line.strip() else '\n' for line in lines]
            
            if lines != original_lines:
                with open(file_path, 'w') as f:
                    f.writelines(lines)
                return True
            
            return False
            
        except Exception as e:
            logger.debug(f"    Manual fix error: {e}")
            return False
    
    def _fix_empty_blocks(self, lines: List[str]) -> List[str]:
        """Add 'pass' to empty blocks."""
        result = []
        block_keywords = ['if ', 'elif ', 'else:', 'def ', 'class ', 
                         'try:', 'except', 'finally:', 'with ', 'for ', 'while ']
        
        i = 0
        while i < len(lines):
            line = lines[i]
            result.append(line)
            stripped = line.strip()
            
            # Check if this line starts a block
            is_block_start = any(stripped.startswith(kw) for kw in block_keywords) and stripped.endswith(':')
            
            if is_block_start and i + 1 < len(lines):
                current_indent = len(line) - len(line.lstrip())
                next_line = lines[i + 1]
                next_stripped = next_line.strip()
                next_indent = len(next_line) - len(next_line.lstrip()) if next_stripped else 0
                
                # If next line is empty, a comment, or has same/less indentation
                needs_pass = False
                if not next_stripped:
                    needs_pass = True
                elif next_stripped.startswith('#'):
                    needs_pass = True
                elif next_indent <= current_indent and not next_stripped.startswith(('elif', 'else', 'except', 'finally')):
                    needs_pass = True
                
                if needs_pass:
                    pass_indent = ' ' * (current_indent + 4)
                    result.append(f"{pass_indent}pass\n")
            
            i += 1
        
        return result
    
    def _fix_block_indentation(self, lines: List[str], error_msg: str) -> List[str]:
        """Fix indentation issues around the error line."""
        # Extract line number from error
        line_match = re.search(r'line (\d+)', error_msg)
        if not line_match:
            return lines
        
        error_line = int(line_match.group(1)) - 1  # 0-indexed
        
        if error_line < 1 or error_line >= len(lines):
            return lines
        
        prev_line = lines[error_line - 1]
        curr_line = lines[error_line]
        
        prev_stripped = prev_line.strip()
        curr_stripped = curr_line.strip()
        
        # If previous line ends with ':', current should be indented
        if prev_stripped.endswith(':') and curr_stripped:
            prev_indent = len(prev_line) - len(prev_line.lstrip())
            curr_indent = len(curr_line) - len(curr_line.lstrip())
            
            if curr_indent <= prev_indent:
                new_indent = ' ' * (prev_indent + 4)
                lines[error_line] = new_indent + curr_stripped + '\n'
        
        return lines


def fix_syntax_after_patch(repo_path: Path, modified_files: List[str]) -> Tuple[bool, List[str]]:
    """
    Fix syntax errors in modified files after applying a patch.
    
    Returns:
        (all_valid, list_of_files_with_errors)
    """
    fixer = SyntaxFixer()
    errors = []
    
    for rel_path in modified_files:
        file_path = repo_path / rel_path
        
        if not file_path.exists():
            continue
        
        if not str(file_path).endswith('.py'):
            continue
        
        is_valid, error_msg = fixer.check_syntax(file_path)
        
        if not is_valid:
            logger.info(f"    🔧 Syntax error in {rel_path}, attempting fix...")
            if not fixer.fix_file(file_path):
                errors.append(rel_path)
                logger.warning(f"    ❌ Could not fix syntax in {rel_path}")
    
    return len(errors) == 0, errors


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_default_results_dir(prompt_type: str, strategy: str) -> Path:
    """Get default results directory for prompt type and strategy."""
    prefix = PROMPT_TYPE_TO_DIR_PREFIX.get(prompt_type, prompt_type)
    return BASE_RESULTS_DIR / f"{prefix}_{strategy}"


def sanitize_model_name(model_name: str) -> str:
    """Convert model name to filesystem-safe string."""
    name = model_name.split("/")[-1]
    for suffix in ["-Instruct-AWQ", "-AWQ", "-Instruct", "-instruct", "-awq"]:
        name = name.replace(suffix, "")
    return re.sub(r'[^\w\-.]', '_', name)


def get_output_filename(model_name: str, prompt_type: str, strategy: str, repetitions: int) -> str:
    """Generate output filename."""
    model_clean = sanitize_model_name(model_name)
    prompt_clean = PROMPT_TYPE_TO_CLEAN_NAME.get(prompt_type, prompt_type)
    return f"{model_clean}_{prompt_clean}_{strategy.capitalize()}_k{repetitions}.json"


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path, 'r') as f:
        return json.load(f)


def save_json(data: dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)


# =============================================================================
# MAIN MEASURER CLASS
# =============================================================================

class LLMPatchMeasurer:
    """
    Measures LLM-generated patches using the same infrastructure as measure_instance.py.
    Includes automatic syntax fixing for common LLM errors.
    """
    
    def __init__(self, original_dataset_path: Path, reduced_dataset_path: Path, country_code: str = "ESP"):
        self.original_dataset_path = Path(original_dataset_path)
        self.reduced_dataset_path = Path(reduced_dataset_path)
        self.country_code = country_code
        
        # Load datasets
        self.original_data = self._load_dataset_as_dict(self.original_dataset_path)
        self.reduced_data = self._load_dataset_as_dict(self.reduced_dataset_path)
        
        # Initialize the SAME measurer used by measure_instance.py
        self.measurer = SWEPerfMeasurer(str(original_dataset_path), country_code=country_code)
        
        # Stats for syntax fixing
        self.syntax_stats = {'fixed': 0, 'failed': 0, 'already_ok': 0}
        
        logger.info(f"LLMPatchMeasurer initialized")
        logger.info(f"  Original dataset: {len(self.original_data)} instances")
        logger.info(f"  Reduced dataset: {len(self.reduced_data)} instances")
    
    def _load_dataset_as_dict(self, path: Path) -> Dict[str, Dict]:
        data = load_json(path)
        instances = data if isinstance(data, list) else data.get("instances", [])
        return {item["instance_id"]: item for item in instances}
    
    def _create_empty_dataset(self, model_name: str, prompt_type: str, strategy: str, repetitions: int) -> Dict:
        prompt_clean = PROMPT_TYPE_TO_CLEAN_NAME.get(prompt_type, prompt_type)
        return {
            'metadata': {
                'name': f'LLM Green Dataset - {model_name} - {prompt_clean} - {strategy}',
                'model': model_name,
                'prompt_type': prompt_clean,
                'strategy': strategy,
                'green_metrics': GREEN_METRICS,
                'efficiency_metrics': EFFICIENCY_METRICS,
                'aggregations': AGGREGATIONS,
                'repetitions': repetitions,
                'creation_date': datetime.now().isoformat(),
                'instance_count': 0,
                'syntax_auto_fix': True  # Flag indicating auto-fix is enabled
            },
            'instances': []
        }
    
    def _is_instance_in_dataset(self, dataset: Dict, instance_id: str) -> bool:
        return any(inst.get('instance_id') == instance_id for inst in dataset.get('instances', []))
    
    def measure_instance(self, instance_id: str, llm_response: str, repetitions: int = 5) -> Optional[Dict]:
        """
        Measure a single instance with LLM patch applied.
        Includes automatic syntax fixing for common LLM errors.
        """
        logger.info(f"  📏 Measuring {instance_id}")
        
        # Get instance from original dataset
        instance = self.original_data.get(instance_id)
        if not instance:
            logger.error(f"    Instance not found in original dataset")
            return None
        
        temp_dir = None
        conda_env = None
        
        try:
            # 1. Setup repository at BASE commit (same as measure_instance.py)
            logger.info(f"    📦 Cloning repository...")
            temp_dir = Path(tempfile.mkdtemp(prefix="llm_meas_"))
            repo_path = self.measurer.setup_repository(instance, temp_dir, instance['base_commit'])
            
            # 2. Apply LLM patch BEFORE installing dependencies
            logger.info(f"    🔧 Applying LLM patch...")
            patch_engine = PatchEngine(repo_path)
            
            # Get candidate files from LLM response
            candidates = list(set(re.findall(r'###\s*([\w/._-]+\.py)', llm_response)))
            if not candidates:
                # Fallback: extract from original patch
                patch_files = re.findall(r'diff --git a/(.*?) b/', instance.get('patch', ''))
                candidates = [f for f in patch_files if f.endswith('.py')]
            
            patch_result = patch_engine.apply_patch(llm_response, candidates)
            
            if not patch_result.success:
                logger.warning(f"    ❌ Failed to apply patch: {patch_result.error_message}")
                return None
            
            logger.info(f"    ✅ Patch applied to: {patch_result.modified_files}")
            
            # 3. NEW: Fix syntax errors in modified files
            logger.info(f"    🔍 Checking syntax...")
            syntax_ok, syntax_errors = fix_syntax_after_patch(repo_path, patch_result.modified_files)
            
            if not syntax_ok:
                logger.warning(f"    ❌ Syntax errors could not be fixed in: {syntax_errors}")
                self.syntax_stats['failed'] += 1
                return None
            else:
                # Check if we had to fix anything
                fixer = SyntaxFixer()
                all_were_ok = True
                for rel_path in patch_result.modified_files:
                    file_path = repo_path / rel_path
                    if file_path.exists() and str(file_path).endswith('.py'):
                        is_valid, _ = fixer.check_syntax(file_path)
                        if not is_valid:
                            all_were_ok = False
                            break
                
                if all_were_ok:
                    self.syntax_stats['already_ok'] += 1
                else:
                    self.syntax_stats['fixed'] += 1
                    logger.info(f"    ✅ Syntax fixed successfully")
            
            # 4. Install dependencies using measure_instance.py's method
            logger.info(f"    📦 Installing dependencies...")
            python_path, conda_env = self.measurer.install_dependencies(
                repo_path=repo_path,
                repo=instance['repo'],
                version=instance['version'],
                commit=instance['base_commit']
            )
            
            if python_path is None:
                logger.warning(f"    ❌ Failed to install dependencies")
                return None
            
            # 5. Get tests from reduced dataset
            reduced_instance = self.reduced_data.get(instance_id, {})
            tests = reduced_instance.get('efficiency_test', [])
            
            if not tests:
                logger.warning(f"    ❌ No tests found")
                return None
            
            logger.info(f"    🧪 Running {len(tests)} tests x {repetitions} repetitions...")
            
            # 6. Run measurements using MetricsCollector
            test_results = {}
            valid_tests = 0
            
            for test in tests:
                test_name = test.split("::")[-1] if "::" in test else test
                
                try:
                    collector = MetricsCollector(
                        repo_path=repo_path,
                        python_path=python_path,
                        test_command=test,
                        repetitions=repetitions,
                        country_code=self.country_code,
                        warmup_runs=1
                    )
                    
                    metrics = collector.collect()
                    
                    if metrics:
                        test_results[test_name] = {"head": metrics}
                        valid_tests += 1
                except Exception as e:
                    logger.debug(f"    Test {test_name} failed: {e}")
            
            if valid_tests == 0:
                logger.warning(f"    ❌ No tests passed")
                return None
            
            # 7. Build result in green dataset format
            result = {
                'instance_id': instance_id,
                'repo': instance.get('repo', ''),
                'efficiency_test': tests,
                'green_metrics': test_results,
                '_green_metadata': {
                    'valid_tests': valid_tests,
                    'total_tests': len(tests),
                    'repetitions': repetitions,
                    'patch_files': patch_result.modified_files,
                    'syntax_auto_fixed': self.syntax_stats['fixed'] > 0,
                    'measurement_date': datetime.now().isoformat()
                }
            }
            
            logger.info(f"    ✅ Measured {valid_tests}/{len(tests)} tests successfully")
            return result
            
        except Exception as e:
            logger.error(f"    ❌ Error: {e}", exc_info=True)
            return None
            
        finally:
            # Cleanup
            if temp_dir and temp_dir.exists():
                shutil.rmtree(temp_dir, ignore_errors=True)
            if conda_env:
                self.measurer.cleanup_conda_env(conda_env)
    
    def measure_strategy(
        self,
        strategy: str,
        prompt_type: str,
        repetitions: int = 5,
        skip_completed: bool = True,
        limit: Optional[int] = None,
        results_dir: Optional[Path] = None,
        model_name: Optional[str] = None
    ) -> Dict:
        """Measure all instances for a strategy."""
        
        logger.info(f"\n{'='*70}")
        logger.info(f"📏 MEASURING: {prompt_type.upper()} - {strategy.upper()}")
        logger.info(f"{'='*70}")
        
        # Reset syntax stats
        self.syntax_stats = {'fixed': 0, 'failed': 0, 'already_ok': 0}
        
        # Determine results directory
        if results_dir:
            exp_results_dir = Path(results_dir)
        else:
            exp_results_dir = get_default_results_dir(prompt_type, strategy)
        
        if not exp_results_dir.exists():
            logger.error(f"Results directory not found: {exp_results_dir}")
            return {"error": f"no_results_directory: {exp_results_dir}"}
        
        result_files = list(exp_results_dir.glob("*.json"))
        logger.info(f"Found {len(result_files)} experiment results in {exp_results_dir}")
        
        # Detect model from results or use provided model_name
        if model_name:
            detected_model = model_name
        else:
            detected_model = DEFAULT_MODEL_NAME
            for rf in result_files:
                try:
                    data = load_json(rf)
                    if data.get("model"):
                        detected_model = data["model"]
                        break
                except:
                    pass
        
        logger.info(f"Model: {detected_model}")
        
        # Output path
        output_filename = get_output_filename(detected_model, prompt_type, strategy, repetitions)
        output_path = GREEN_OUTPUT_DIR / output_filename
        logger.info(f"Output: {output_path}")
        
        # Load or create dataset
        if output_path.exists():
            output_dataset = load_json(output_path)
            logger.info(f"Loaded existing: {len(output_dataset.get('instances', []))} instances")
        else:
            output_dataset = self._create_empty_dataset(detected_model, prompt_type, strategy, repetitions)
            logger.info(f"Created new dataset")
        
        # Filter successful patches
        to_measure = []
        for result_file in result_files:
            try:
                exp_result = load_json(result_file)
                instance_id = exp_result.get("instance_id")
                
                # Check for success - handle both old and new formats
                patch_result = exp_result.get("patch_result", {})
                if isinstance(patch_result, dict):
                    is_success = patch_result.get("success", False)
                else:
                    is_success = exp_result.get("status") == "success"
                
                if not is_success:
                    continue
                
                if skip_completed and self._is_instance_in_dataset(output_dataset, instance_id):
                    continue
                
                # Get LLM response - handle different formats
                llm_response = exp_result.get("llm_response", "")
                if not llm_response:
                    llm_response = exp_result.get("patch_content", "")
                if not llm_response:
                    all_responses = exp_result.get("all_responses", [])
                    if all_responses:
                        llm_response = all_responses[-1]
                if not llm_response:
                    iterations = exp_result.get("iterations", [])
                    if iterations:
                        llm_response = iterations[-1].get("patch_content", "")
                
                if not llm_response:
                    continue
                
                to_measure.append({
                    "instance_id": instance_id,
                    "llm_response": llm_response
                })
                
                if limit and len(to_measure) >= limit:
                    break
            except Exception as e:
                logger.warning(f"Error reading {result_file.name}: {e}")
        
        already_done = len(output_dataset.get('instances', []))
        logger.info(f"Already measured: {already_done}")
        logger.info(f"To measure: {len(to_measure)}")
        
        if not to_measure:
            logger.info(f"✅ Nothing to measure!")
            return {"total": len(result_files), "already_done": already_done, 
                    "measured": 0, "success": 0, "failed": 0}
        
        # Measure
        stats = {"total": len(result_files), "already_done": already_done,
                 "measured": 0, "success": 0, "failed": 0, "timing": [],
                 "syntax_fixed": 0, "syntax_failed": 0}
        
        for idx, item in enumerate(to_measure):
            instance_id = item["instance_id"]
            logger.info(f"\n[{idx+1}/{len(to_measure)}] {instance_id}")
            
            start_time = time.time()
            result = self.measure_instance(instance_id, item["llm_response"], repetitions)
            elapsed = time.time() - start_time
            
            stats["timing"].append(elapsed)
            stats["measured"] += 1
            
            if result:
                stats["success"] += 1
                
                # Update dataset
                output_dataset['instances'] = [
                    i for i in output_dataset['instances']
                    if i.get('instance_id') != instance_id
                ]
                output_dataset['instances'].append(result)
                output_dataset['metadata']['last_updated'] = datetime.now().isoformat()
                output_dataset['metadata']['instance_count'] = len(output_dataset['instances'])
                
                save_json(output_dataset, output_path)
                logger.info(f"  💾 Saved ({elapsed:.1f}s)")
            else:
                stats["failed"] += 1
                logger.warning(f"  ❌ Failed ({elapsed:.1f}s)")
        
        # Update syntax stats
        stats["syntax_fixed"] = self.syntax_stats['fixed']
        stats["syntax_failed"] = self.syntax_stats['failed']
        stats["syntax_already_ok"] = self.syntax_stats['already_ok']
        
        logger.info(f"\n✅ Complete! Output: {output_path}")
        logger.info(f"   Instances: {len(output_dataset['instances'])}")
        logger.info(f"   Syntax stats: {self.syntax_stats}")
        
        return stats
    
    def run(self, strategies: List[str], prompt_type: str = "zero_shot",
            repetitions: int = 5, skip_completed: bool = True, limit: Optional[int] = None,
            results_dir: Optional[Path] = None, model_name: Optional[str] = None) -> Dict:
        """Run measurements for strategies."""
        
        start_time = time.time()
        summary = {"prompt_type": prompt_type, "model": model_name or DEFAULT_MODEL_NAME, "results": {}}
        
        for strategy in strategies:
            stats = self.measure_strategy(
                strategy=strategy,
                prompt_type=prompt_type,
                repetitions=repetitions,
                skip_completed=skip_completed,
                limit=limit,
                results_dir=results_dir,
                model_name=model_name
            )
            summary["results"][strategy] = stats
        
        summary["duration_seconds"] = time.time() - start_time
        
        # Print summary
        logger.info(f"\n{'='*70}")
        logger.info(f"📊 SUMMARY - {prompt_type.upper()} - {summary['model']}")
        logger.info(f"{'='*70}")
        for strategy, stats in summary["results"].items():
            if "error" in stats:
                logger.info(f"{strategy}: ERROR - {stats['error']}")
            else:
                logger.info(f"{strategy}: {stats.get('success',0)} success, {stats.get('failed',0)} failed")
                logger.info(f"  Syntax: {stats.get('syntax_fixed',0)} fixed, {stats.get('syntax_failed',0)} unfixable")
        logger.info(f"Duration: {summary['duration_seconds']/60:.1f} minutes")
        
        return summary


def main():
    parser = argparse.ArgumentParser(
        description="Measure LLM patches for energy consumption (with automatic syntax fixing)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Measure Zero-Shot Oracle patches
  python measure_llm_patches.py --strategy oracle --prompt-type zero_shot -k 3
  
  # Measure Self-Collaboration patches
  python measure_llm_patches.py --strategy oracle --prompt-type self_collab -k 3
  
  # Measure LDB patches
  python measure_llm_patches.py --strategy realistic --prompt-type ldb -k 3
  
  # Measure both strategies
  python measure_llm_patches.py --strategy both --prompt-type cot -k 3
  
  # Multi-model support
  python measure_llm_patches.py --strategy oracle --prompt-type zero_shot -k 3 \
      --results-dir results/DeepSeek-Coder-V2/zs_oracle --model-name DeepSeek-Coder-V2
        """
    )
    parser.add_argument('--strategy', '-s', 
                        choices=['oracle', 'realistic', 'both'], 
                        default='oracle',
                        help='Strategy to measure')
    parser.add_argument('--prompt-type', '-p', 
                        choices=['zero_shot', 'cot', 'self_collab', 'ldb'], 
                        default='zero_shot',
                        help='Prompt type to measure')
    parser.add_argument('--repetitions', '-k', type=int, default=3,
                        help='Number of measurement repetitions (default: 3)')
    parser.add_argument('--limit', '-l', type=int, default=None,
                        help='Limit number of instances to measure')
    parser.add_argument('--no-skip', action='store_true',
                        help='Re-measure already completed instances')
    parser.add_argument('--dataset', '-d', type=str, default=str(DEFAULT_DATASET),
                        help='Path to reduced dataset (default: swe_perf_reduced.json)')
    parser.add_argument('--results-dir', '-r', type=str, default=None,
                        help='Custom results directory (for multi-model support)')
    parser.add_argument('--model-name', '-m', type=str, default=None,
                        help='Model name override (for multi-model support)')
    
    args = parser.parse_args()
    
    strategies = ['oracle', 'realistic'] if args.strategy == 'both' else [args.strategy]
    reduced_dataset = Path(args.dataset)
    
    if not reduced_dataset.exists():
        print(f"❌ Dataset not found: {reduced_dataset}")
        sys.exit(1)
    
    measurer = LLMPatchMeasurer(
        original_dataset_path=ORIGINAL_DATASET,
        reduced_dataset_path=reduced_dataset
    )
    
    measurer.run(
        strategies=strategies,
        prompt_type=args.prompt_type,
        repetitions=args.repetitions,
        skip_completed=not args.no_skip,
        limit=args.limit,
        results_dir=Path(args.results_dir) if args.results_dir else None,
        model_name=args.model_name
    )


if __name__ == "__main__":
    main()