"""
Syntax Auto-Fixer for LLM-generated patches.

Fixes common syntax errors in Python code generated by LLMs:
- IndentationError: expected an indented block
- IndentationError: unexpected unindent
- Mixed tabs/spaces
- Trailing whitespace issues

Usage:
    from syntax_fixer import SyntaxFixer
    
    fixer = SyntaxFixer()
    success = fixer.fix_file(Path("path/to/file.py"))
"""

import subprocess
import re
import tempfile
import shutil
from pathlib import Path
from typing import Tuple, Optional, List
import logging

logger = logging.getLogger(__name__)


class SyntaxFixer:
    """Auto-fixes common syntax errors in Python files."""
    
    def __init__(self):
        self.fixes_applied = []
    
    def check_syntax(self, file_path: Path) -> Tuple[bool, str]:
        """
        Check if a Python file has valid syntax.
        
        Returns:
            (is_valid, error_message)
        """
        result = subprocess.run(
            ['python', '-m', 'py_compile', str(file_path)],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            return True, ""
        
        error_msg = result.stderr or result.stdout
        return False, error_msg
    
    def fix_file(self, file_path: Path) -> bool:
        """
        Attempt to fix syntax errors in a Python file.
        
        Returns:
            True if file has valid syntax after fixes, False otherwise
        """
        file_path = Path(file_path)
        
        if not file_path.exists():
            logger.warning(f"File not found: {file_path}")
            return False
        
        # Step 1: Check if already valid
        is_valid, error_msg = self.check_syntax(file_path)
        if is_valid:
            return True
        
        logger.info(f"Fixing syntax errors in {file_path.name}")
        logger.debug(f"Error: {error_msg[:200]}")
        
        # Step 2: Try autopep8 (aggressive mode)
        if self._try_autopep8(file_path):
            is_valid, _ = self.check_syntax(file_path)
            if is_valid:
                self.fixes_applied.append(('autopep8', str(file_path)))
                logger.info(f"  ✅ Fixed with autopep8")
                return True
        
        # Step 3: Try manual fixes based on error type
        if self._try_manual_fixes(file_path, error_msg):
            is_valid, _ = self.check_syntax(file_path)
            if is_valid:
                self.fixes_applied.append(('manual', str(file_path)))
                logger.info(f"  ✅ Fixed with manual fixes")
                return True
        
        # Step 4: Try autopep8 again after manual fixes
        if self._try_autopep8(file_path):
            is_valid, _ = self.check_syntax(file_path)
            if is_valid:
                self.fixes_applied.append(('autopep8+manual', str(file_path)))
                logger.info(f"  ✅ Fixed with autopep8 after manual fixes")
                return True
        
        logger.warning(f"  ❌ Could not fix syntax errors in {file_path.name}")
        return False
    
    def _try_autopep8(self, file_path: Path) -> bool:
        """Try to fix with autopep8."""
        try:
            # First, try standard autopep8
            result = subprocess.run(
                ['autopep8', '--in-place', '--aggressive', '--aggressive', 
                 '--max-line-length', '120', str(file_path)],
                capture_output=True,
                text=True,
                timeout=30
            )
            return result.returncode == 0
        except FileNotFoundError:
            logger.warning("autopep8 not installed, skipping")
            return False
        except subprocess.TimeoutExpired:
            logger.warning("autopep8 timed out")
            return False
        except Exception as e:
            logger.warning(f"autopep8 error: {e}")
            return False
    
    def _try_manual_fixes(self, file_path: Path, error_msg: str) -> bool:
        """
        Try to manually fix common syntax errors.
        
        Handles:
        - "expected an indented block" → add 'pass' statement
        - "unexpected unindent" → fix indentation
        - Empty blocks after if/else/def/class/try/except/finally/with/for/while
        """
        try:
            with open(file_path, 'r') as f:
                lines = f.readlines()
            
            modified = False
            
            # Extract line number from error message
            line_match = re.search(r'line (\d+)', error_msg)
            error_line = int(line_match.group(1)) if line_match else None
            
            # Fix 1: Add 'pass' after empty block statements
            modified |= self._fix_empty_blocks(lines)
            
            # Fix 2: Fix indentation issues around the error line
            if error_line:
                modified |= self._fix_indentation_at_line(lines, error_line)
            
            # Fix 3: Normalize all indentation (tabs to spaces)
            modified |= self._normalize_indentation(lines)
            
            # Fix 4: Remove trailing whitespace
            modified |= self._remove_trailing_whitespace(lines)
            
            if modified:
                with open(file_path, 'w') as f:
                    f.writelines(lines)
                return True
            
            return False
            
        except Exception as e:
            logger.warning(f"Manual fix error: {e}")
            return False
    
    def _fix_empty_blocks(self, lines: List[str]) -> bool:
        """Add 'pass' to empty blocks."""
        modified = False
        block_keywords = ['if ', 'elif ', 'else:', 'def ', 'class ', 
                         'try:', 'except', 'finally:', 'with ', 'for ', 'while ']
        
        i = 0
        while i < len(lines) - 1:
            line = lines[i]
            stripped = line.strip()
            
            # Check if this line starts a block
            is_block_start = any(stripped.startswith(kw) for kw in block_keywords) and stripped.endswith(':')
            
            if is_block_start:
                # Get current indentation
                current_indent = len(line) - len(line.lstrip())
                next_line = lines[i + 1] if i + 1 < len(lines) else ""
                next_stripped = next_line.strip()
                next_indent = len(next_line) - len(next_line.lstrip()) if next_stripped else 0
                
                # Check if next line is empty or has same/less indentation (empty block)
                if not next_stripped or (next_indent <= current_indent and next_stripped and 
                                         not next_stripped.startswith('#')):
                    # Insert 'pass' with proper indentation
                    pass_indent = ' ' * (current_indent + 4)
                    lines.insert(i + 1, f"{pass_indent}pass\n")
                    modified = True
                    logger.debug(f"  Added 'pass' after line {i + 1}")
            
            i += 1
        
        return modified
    
    def _fix_indentation_at_line(self, lines: List[str], error_line: int) -> bool:
        """Fix indentation issues around the error line."""
        modified = False
        
        if error_line < 1 or error_line > len(lines):
            return False
        
        idx = error_line - 1  # Convert to 0-indexed
        
        # Look at the line and surrounding context
        if idx > 0:
            prev_line = lines[idx - 1]
            curr_line = lines[idx]
            
            prev_stripped = prev_line.strip()
            curr_stripped = curr_line.strip()
            
            # If previous line ends with ':', current should be indented more
            if prev_stripped.endswith(':') and curr_stripped:
                prev_indent = len(prev_line) - len(prev_line.lstrip())
                curr_indent = len(curr_line) - len(curr_line.lstrip())
                
                if curr_indent <= prev_indent:
                    # Fix indentation
                    new_indent = ' ' * (prev_indent + 4)
                    lines[idx] = new_indent + curr_stripped + '\n'
                    modified = True
                    logger.debug(f"  Fixed indentation at line {error_line}")
        
        return modified
    
    def _normalize_indentation(self, lines: List[str]) -> bool:
        """Convert all tabs to 4 spaces."""
        modified = False
        
        for i, line in enumerate(lines):
            if '\t' in line:
                # Replace tabs with 4 spaces
                new_line = line.replace('\t', '    ')
                if new_line != line:
                    lines[i] = new_line
                    modified = True
        
        return modified
    
    def _remove_trailing_whitespace(self, lines: List[str]) -> bool:
        """Remove trailing whitespace from all lines."""
        modified = False
        
        for i, line in enumerate(lines):
            stripped = line.rstrip() + '\n' if line.strip() else '\n'
            if stripped != line:
                lines[i] = stripped
                modified = True
        
        return modified
    
    def fix_files(self, file_paths: List[Path]) -> Tuple[int, int]:
        """
        Fix multiple files.
        
        Returns:
            (num_fixed, num_failed)
        """
        fixed = 0
        failed = 0
        
        for file_path in file_paths:
            if self.fix_file(file_path):
                fixed += 1
            else:
                failed += 1
        
        return fixed, failed


def fix_syntax_after_patch(repo_path: Path, modified_files: List[str]) -> Tuple[bool, List[str]]:
    """
    Convenience function to fix syntax errors after applying a patch.
    
    Args:
        repo_path: Path to the repository
        modified_files: List of modified file paths (relative to repo)
    
    Returns:
        (all_valid, list_of_files_with_errors)
    """
    fixer = SyntaxFixer()
    errors = []
    
    for rel_path in modified_files:
        file_path = repo_path / rel_path
        
        if not file_path.exists():
            continue
        
        if not file_path.suffix == '.py':
            continue
        
        is_valid, error_msg = fixer.check_syntax(file_path)
        
        if not is_valid:
            # Try to fix
            if not fixer.fix_file(file_path):
                errors.append(rel_path)
    
    return len(errors) == 0, errors


# Test function
if __name__ == "__main__":
    import sys
    
    logging.basicConfig(level=logging.DEBUG)
    
    if len(sys.argv) > 1:
        fixer = SyntaxFixer()
        file_path = Path(sys.argv[1])
        
        print(f"Checking {file_path}...")
        is_valid, error = fixer.check_syntax(file_path)
        
        if is_valid:
            print("✅ Syntax is valid")
        else:
            print(f"❌ Syntax error: {error[:200]}")
            print("\nAttempting to fix...")
            
            if fixer.fix_file(file_path):
                print("✅ Fixed successfully!")
            else:
                print("❌ Could not fix")
    else:
        print("Usage: python syntax_fixer.py <file.py>")